timestamp: 2020-03-01T04:20:37.315922
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57538
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:21:32.478002
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57759
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:21:43.149939
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57792
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:22:18.012054
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57828
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:23:39.286175
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57872
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:23:49.820091
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --version
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--version']
pid: 57908
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:24:02.816276
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants']
pid: 57943
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:24:20.614021
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --print-exception-stacktrace
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--print-exception-stacktrace']
pid: 57978
Exception caught: (builtins.Exception)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 103, in run
    options_bootstrapper=options_bootstrapper
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 173, in create
    options
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 107, in _maybe_init_graph_session
    build_config
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 291, in setup_legacy_graph
    execution_options=ExecutionOptions.from_bootstrap_options(bootstrap_options),
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 434, in setup_legacy_graph_extended
    visualize_to_dir=bootstrap_options.native_engine_visualize_to,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 107, in __init__
    execution_options=execution_options,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/native.py", line 982, in new_scheduler
    raise value

Exception message: Could not initialize store for process cache: "Error making env for store at \"/Users/Omkar/.cache/pants/lmdb_store/processes/a\": Too many open files"

timestamp: 2020-03-01T04:35:15.869135
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants --target-spec-file=/private/var/folders/hx/27cf965s6l7fkgxfc63ll94r0000gp/T/pants_target_specs2.in --no-quiet export-dep-as-jar --output-file=/private/var/folders/hx/27cf965s6l7fkgxfc63ll94r0000gp/T/pants_depmap_run2.out --formatted --export-libraries-sources --export-libraries-javadocs
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', '--target-spec-file=/private/var/folders/hx/27cf965s6l7fkgxfc63ll94r0000gp/T/pants_target_specs2.in', '--no-quiet', 'export-dep-as-jar', '--output-file=/private/var/folders/hx/27cf965s6l7fkgxfc63ll94r0000gp/T/pants_depmap_run2.out', '--formatted', '--export-libraries-sources', '--export-libraries-javadocs']
pid: 59395
Exception caught: (pants.build_graph.address_lookup_error.AddressLookupError)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 106, in run
    return runner.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 253, in run
    self._run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 332, in _run
    goal_runner_result = self._maybe_run_v1()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 282, in _maybe_run_v1
    self._exiter
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/goal_runner.py", line 116, in create
    goals, context = self._setup_context()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/goal_runner.py", line 86, in _setup_context
    self._root_dir
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 244, in create_build_graph
    for _ in graph.inject_roots_closure(target_roots):
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 194, in inject_roots_closure
    for address in self._inject_specs(target_roots.specs):
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 246, in _inject_specs
    [specs])
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/legacy/graph.py", line 213, in _resolve_context
    'Build graph construction failed: {} {}'.format(type(e).__name__, str(e))

Exception message: Build graph construction failed: ExecutionError 1 Exception encountered:
  AddressLookupError: Spec DescendantAddresses(directory='') does not match any targets.

timestamp: 2020-03-01T12:48:43.283441
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants list ::
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', 'list', '::']
pid: 60186
Exception caught: (pants.engine.scheduler.ExecutionError)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 106, in run
    return runner.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 253, in run
    self._run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 330, in _run
    engine_result = self._maybe_run_v2()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 301, in _maybe_run_v2
    self._target_roots,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 224, in run_console_rules
    exit_code = self.scheduler_session.run_console_rule(goal_product, params)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 471, in run_console_rule
    self._trace_on_error([exc], request)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 456, in _trace_on_error
    unique_exceptions

Exception message: 1 Exception encountered:
  AddressLookupError: Spec DescendantAddresses(directory='') does not match any targets.

timestamp: 2020-03-01T12:48:48.304926
process title: /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/python /Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants list ::
sys.argv: ['/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants', 'list', '::']
pid: 60218
Exception caught: (pants.engine.scheduler.ExecutionError)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/bin/pants", line 8, in <module>
    sys.exit(main())
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 81, in main
    PantsLoader.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 77, in run
    cls.load_and_execute(entrypoint)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_loader.py", line 70, in load_and_execute
    entrypoint_main()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_exe.py", line 32, in main
    PantsRunner(start_time=start_time).run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/pants_runner.py", line 106, in run
    return runner.run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 253, in run
    self._run()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 330, in _run
    engine_result = self._maybe_run_v2()
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/bin/local_pants_runner.py", line 301, in _maybe_run_v2
    self._target_roots,
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/init/engine_initializer.py", line 224, in run_console_rules
    exit_code = self.scheduler_session.run_console_rule(goal_product, params)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 471, in run_console_rule
    self._trace_on_error([exc], request)
  File "/Users/Omkar/.cache/pants/setup/bootstrap-Darwin-x86_64/1.24.0_py37/lib/python3.7/site-packages/pants/engine/scheduler.py", line 456, in _trace_on_error
    unique_exceptions

Exception message: 1 Exception encountered:
  AddressLookupError: Spec DescendantAddresses(directory='') does not match any targets.

